#!/bin/sh
echo "Type checking..."
bun run typecheck:desktop

echo "Running unit tests..."
bun run test:desktop

echo "Running cargo clippy..."
cargo clippy --manifest-path apps/desktop/src-tauri/Cargo.toml -- -D warnings